#!/usr/bin/env python3
"""Inline src/web/ into a single gzipped page and emit src/ino/hidra/page.h.

The firmware serves one blob with Content-Encoding: gzip. Gzipping matters here: the sketch
already sits at ~80% of the default partition, and the keyboard page compresses roughly 4x.

Usage:  python3 tools/build_page.py
"""

import gzip
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB = ROOT / "src" / "web"
OUT = ROOT / "src" / "ino" / "hidra" / "page.h"


def strip_comments(js: str) -> str:
    """Drop full-line // comments and blank lines.

    Deliberately conservative: only lines whose first non-space characters are `//`, so a `//`
    inside a string literal (`'ws://' + location.host`) is never touched.
    """
    out = []
    for line in js.splitlines():
        s = line.strip()
        if s.startswith("//") or not s:
            continue
        out.append(line)
    return "\n".join(out)


def inline(html: str) -> str:
    def css(m):
        text = (WEB / m.group(1)).read_text()
        return "<style>\n" + text + "\n</style>"

    def js(m):
        text = strip_comments((WEB / m.group(1)).read_text())
        return "<script>\n" + text + "\n</script>"

    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', css, html)
    html = re.sub(r'<script src="([^"]+)"></script>', js, html)
    return html


def to_c_array(data: bytes, name: str) -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = ", ".join("0x%02x" % b for b in data[i:i + 16])
        lines.append("  " + chunk + ",")
    return (
        "const uint8_t %s[] PROGMEM = {\n%s\n};\n"
        "const size_t %s_LEN = %d;\n" % (name, "\n".join(lines), name, len(data))
    )


def main():
    index = WEB / "index.html"
    if not index.exists():
        sys.exit("missing %s" % index)

    html = inline(index.read_text())
    raw = html.encode("utf-8")
    packed = gzip.compress(raw, 9)

    header = (
        "// GENERATED by tools/build_page.py — do not edit.\n"
        "// Source: src/web/{index.html,style.css,keymap.js,transport.js,app.js}\n"
        "// Served with Content-Encoding: gzip.\n"
        "#pragma once\n"
        "#include <pgmspace.h>\n\n"
        + to_c_array(packed, "INDEX_HTML_GZ")
    )
    OUT.write_text(header)

    print("page: %d bytes raw -> %d bytes gzip (%.1f%%)"
          % (len(raw), len(packed), 100.0 * len(packed) / len(raw)))
    print("wrote %s" % OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
